# Generated by Django 3.0.4 on 2020-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
